version: "3"

services:
  softether-server:
    container_name: ${VPN_CONTAINER_NAME}
    build:
      context: ./softether
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    volumes:
      - ./softether/auth:/root/mnt
    ports:
      - 1194:${VPN_PORT}/udp
      - 5555:5555/tcp
    tty: true
    network_mode: "host"

  radius-server:
    container_name: ${RADIUS_CONTAINER_NAME}
    build:
      context: ./radius
      dockerfile: Dockerfile
    volumes:
      - ./radius/auth:/root/mnt
    tty: true
    networks:
      app_net:
        ipv4_address: ${RADIUS_ADDR}

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${APP_NETWORK_ADDR}