version: "3"

services:
  softether-server:
    container_name: softether
    build:
      context: ./softether
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    volumes:
      - ~/containers/softether/setting:/root/mnt
    ports:
      - 1194:1194/udp
      - 5555:5555/tcp
    tty: true
    network_mode: "host"

  radius-server:
    container_name: radius
    build:
      context: ./radius
      dockerfile: Dockerfile
    volumes:
      - ~/containers/radius/auth:/user/mnt
    tty: true
    networks:
      app_net:
        ipv4_address: 172.30.0.5

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24